document.getElementById("#otstoi")
document.getElementById("#otstoi")
document.getElementById("#otstoi")
document.getElementById("#otstoi")
document.getElementById("#otstoi")
document.getElementById("#otstoi")